// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUr2FKLuu0ykOUi6llDMSm2eIkJ0EsbpY',
    appId: '1:775576034236:android:29bcde6ad762ae2702e9b9',
    messagingSenderId: '775576034236',
    projectId: 'brilloconnetz',
    storageBucket: 'brilloconnetz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKr5UTfdqDom7aoiIVMYxlN9YXIW1SksM',
    appId: '1:775576034236:ios:47486dae6250dded02e9b9',
    messagingSenderId: '775576034236',
    projectId: 'brilloconnetz',
    storageBucket: 'brilloconnetz.appspot.com',
    androidClientId: '775576034236-dtj6srslkfqkontu1kas907la3d7g493.apps.googleusercontent.com',
    iosClientId: '775576034236-jpvs4spodkbh8452lfpngqig4oq32o1a.apps.googleusercontent.com',
    iosBundleId: 'net.brilloconnetz.app',
  );
}
